default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("RAILS_DB_USER", "") %>
  password: <%= ENV.fetch("RAILS_DB_PASSWORD", "") %>
  host:  <%= ENV.fetch("RAILS_DB_HOST", "localhost") %>

development:
  <<: *default
  database: react_rails_api_backend_development

test:
  <<: *default
  database: react_rails_api_backend_test

production:
  <<: *default
  database: <%= ENV['RAILS_DB_DATABASE'] %>
  username: <%= ENV['RAILS_DB_USER_NAME'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>
  host:  <%= ENV['RAILS_DB_HOST'] %>
